spring:
  application:
    name: eureka-server
    
#server:
#  port: 2001
  
eureka:
  server:
            #开发环境下,关闭保护模式
    enable-self-preservation: false
#  instance:
    #eureka集群中,通过hostname来区分不同的服务器
#    hostname: eureka1
#  client:
            #避免向自己注册自己
#    register-with-eureka: false
            #避免从自己的注册表,拉去注册信息
#    fetch-registry: false

---
spring:
  profiles: eureka1

server:
  port: 2001
  
# eureka1 向 eureka2 注册
eureka:
  instance:
    hostname: eureka1
  client:
    service-url: 
      defaultZone: http://eureka2:2002/eureka

---
spring:
  profiles: eureka2

server:
  port: 2002
  
# eureka2 向 eureka1 注册
eureka:
  instance:
    hostname: eureka2
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka